name: Deploy to Staging

on:
  push:
    branches: ['develop']
  workflow_dispatch:
    inputs:
      deploy-msg:
        description: 'Deploy Message (visible in Netlify)'
        required: true

env:
  REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
  REACT_APP_API_CLIENT_ID: ${{ secrets.REACT_APP_API_CLIENT_ID }}
  REACT_APP_API_CLIENT_SECRET: ${{ secrets.REACT_APP_API_CLIENT_SECRET }}

jobs:
  deploy:
    name: Build and Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          deploy-message: "Deploy from GitHub Actions: ${{ github.event.inputs.deploy-msg }}"
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

  deploy-storybook:
    name: Build and Deploy Storybook to Staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Build Storybook
        run: npm run storybook:build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './storybook-static'
          alias: storybook
          deploy-message: 'Deploy Storybook from GitHub Actions: ${{ github.event.inputs.deploy-msg }}'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
