name: Test

on: pull_request

jobs:
  test:
    name: Run linters and tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run codebase:lint

      - name: Run unit tests
        run: npm test -- --coverage

      - name: Run component tests
        run: npx start-server-and-test start 3000 cypress:component

      - name: Run e2e tests
        run: npx start-server-and-test start 3000 cypress:e2e

      - name: Merge code coverage reports
        run: npm run test:merge-coverage

      - name: Danger
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
